name: oag-cae
channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  # --- core ---
  - python=3.9

  # --- pytorch ---
  - pytorch=2.2.*
  - torchvision=0.17.*
  - torchaudio=2.2.*
  - pytorch-cuda=11.8


  # --- scientific stack ---
  - numpy<2.0
  - scipy<1.12
  - scikit-learn>=1.2,<1.7
  - pandas>=2.0
  - matplotlib>=3.7

  # --- explainability ---
  - shap>=0.44

  # --- neuroimaging utils ---
  - nibabel
  - nilearn
  - networkx

  # --- misc ---
  - sympy
  - joblib
  - pyyaml
  - tqdm

  # --- pip-only packages ---
  - pip
  - pip:
      - monai==1.3.0
      - nipype==1.8.6
